### ISSUE TITLE
Examples wont' run

### ISSUE THREAD

**Issue by mwz293** [jasonwjones/essbasepy#11]
I am running the `mdxtest.py` example and the code is failing on line 2. The below code snippet is the error that is being thrown. Can't seem to find that particular dll on my computer either (thoughts on where I can download it?). I am up for any questions/suggestions: spent a ton of time testing various configurations... to no avail. This "issue" isn't so much a problem with the `essbasepy` code as it is with getting it to run on my computer. Thanks in advance.

Running Python 2.7.5

`        __maxldll = find_library('essmaxlu')
        if __maxldll:
            print ("Using Maxl DLL in {DLLpath}".format(DLLpath = __maxldll))
            self.maxl = cdll.LoadLibrary(__maxldll)
        else:
            print ("maxl DLL not found")
            raise SystemExit
`

**Comment by mwz293** [comment]
My issue was that the files in `C:\Python27_64;C:\Oracle\Middleware\EPMSystem11R1\common\EssbaseRTC-64\11.1.2.0\bin` were 32-bit python. Once I matched the python bit version to the correct bit version in the essbase dlls, everything worked like a charm.

**Comment by jasonwjones** [comment]
Excellent -- glad you were able to resolve the issue. On a separate note, I'm not sure what the future of this tool looks like what with OAC and other things and how MaxL works/will work, but time will tell. It might make sense to write something in Python to consume the REST API.
