### ISSUE TITLE
dimension member delimiter

### ISSUE THREAD

**Issue by Bachatero** [jasonwjones/essbasepy#14]
Hello everyone.

This is one row (tuple?) returned by my esb.execute(statement):

(January, BE08008309-North, Central and East HQ Mtmt Adj., 2014, ICP, US Dollar, TOPC1, TOPC2, TOPC3, ACTUAL, ACCUMDEP - Accumulated Depreciation)	4321.878

Can I somehow change the member delimiter to a pipe  "|" instead of a comma "," ? 
In other words, is it possible to alter my MDX query/Essbase.py to separate members with different separator than comma or optionally enclose them within double quotes ?

The problem I'm facing is that some of my members contain commas in their names, e.g. "BE08008309-North, Central and East HQ Mtmt Adj." in my example above includes a comma. 

I would like to have my returned row read like this instead:

(January | BE08008309-North, Central and East HQ Mtmt Adj.| 2014| ICP| US Dollar| TOPC1| TOPC2| TOPC3| ACTUAL| ACCUMDEP - Accumulated Depreciation)	4321.878
or 
("January", "BE08008309-North, Central and East HQ Mtmt Adj.", "2014", "ICP", "US Dollar", "TOPC1", "TOPC2", "TOPC3", "ACTUAL", "ACCUMDEP - Accumulated Depreciation")	4321.878

Thank you.
Marcel

**Comment by nurzen** [comment]
Hello,
i dont think thats possible because Essbase,py is using the DLL provided by Oracle. You get the same output when you query via Essbase Administration Console. I think the only way to achieve this goal is by using the Java API. You can use this via jython i you prefer python as programming language.

Greets

**Comment by Bachatero** [comment]
Hi, 
ok, I understand. Thank you, Kev.

Anyway, I was wondering then if there isn't a way of rewriting my MDX query using some kind of concatenation to reach the same goal. 

The query which produces the output as mentioned above: 

(January, BE08008309-North, Central and East HQ Mtmt Adj., 2014, ICP, US Dollar, TOPC1, TOPC2, TOPC3, ACTUAL, ACCUMDEP - Accumulated Depreciation)	4321.878

is the following:

SELECT 
{([Version].[FINAL])} ON COLUMNS
,crossjoin(crossjoin(crossjoin(crossjoin(crossjoin(crossjoin(crossjoin(crossjoin(crossjoin({ [Period].[Jan],[Period].[Dec],[Period].[Sep] },{  [Entity].[BE08008309], [Entity].[BTSEMEALA] }),{ [Years].[2018],[Years].[2017],[Years].[2014] }),{ [ICP].[ICP] }),{ [Currency].[USD] }),{ [Custom1].[TOPC1] }),{ [Custom2].[TOPC2] }),{ [Custom3].[TOPC3] }),{ [Scenario].[Actual],[Scenario].[Junfor],[Scenario].[PlanRestate] }),{ [Account].[RF_ACCUMDEP],[Account].[COSAMORT] })
ON ROWS FROM [EssRptg.EssRptg]

Could this be rewritten to concatenate every member with a pipe "|" for instance?

(|January|, |BE08008309-North, Central and East HQ Mtmt Adj.|, |2014|, |ICP|, |US Dollar|, |TOPC1|, |TOPC2|, |TOPC3|, |ACTUAL, ACCUMDEP - Accumulated Depreciation|)	4321.878

Your help would be much appreciated.

Thank you very much.

Marcel

**Comment by Bachatero** [comment]
Hi, 

fyi, I've found a WA rewritting my MDX query to include  DIMENSION PROPERTIES [Period].[MEMBER_NAME],[Period].[MEMBER_ALIAS], [Entity.[MEMBER_NAME],[Entity].[MEMBER_ALIAS], and so forth.

my query would then look like the following:

SELECT
{([Version].[FINAL])} ON COLUMNS
,crossjoin(crossjoin(crossjoin(crossjoin(crossjoin(crossjoin(crossjoin(crossjoin(crossjoin({ [Period].[Jan],[Period].[Dec],[Period].[Sep] },{ [Entity].[BE08008309], [Entity].[BTSEMEALA] }),{ [Years].[2018],[Years].[2017],[Years].[2014] }),{ [ICP].[ICP] }),{ [Currency].[USD] }),{ [Custom1].[TOPC1] }),{ [Custom2].[TOPC2] }),{ [Custom3].[TOPC3] }),{ [Scenario].[Actual],[Scenario].[Junfor],[Scenario].[PlanRestate] }),{ [Account].[RF_ACCUMDEP],[Account].[COSAMORT] })  DIMENSION PROPERTIES [Period].[MEMBER_NAME],[Period].[MEMBER_ALIAS], [Entity].[MEMBER_NAME],[Entity].[MEMBER_ALIAS],[Years].[MEMBER_NAME],[ICP].[MEMBER_NAME],[Currency].[MEMBER_NAME],[Currency].[MEMBER_ALIAS],[Custom1].[MEMBER_NAME],[Custom1].[MEMBER_ALIAS],[Custom2].[MEMBER_NAME],[Custom2].[MEMBER_ALIAS],[Custom3].[MEMBER_NAME],[Scenario].[MEMBER_NAME],[Account].[MEMBER_NAME],[Account].[MEMBER_ALIAS] ON ROWS FROM [EssRptg.EssRptg]

Then I parsed the output of the query while removing unnecessary "[MEMBER_NAME] = " and "[MEMBER_ALIAS] = "  strings and by splitting the string by "type: STRING," I was ready to overcome my issue with "comma" inside some of my Member columns. 

Cheers.
Marcel
