### ISSUE TITLE
Should rows() contain the axis after a do() ?

### ISSUE THREAD

**Issue by flummoxify** [jasonwjones/essbasepy#15]
Hi,
When I do an execute() of a mdx statement it is printing the results out:
*********
Axis-1  (Qtr1)  (Qtr2)  (Qtr3)  (Qtr4)
------  ------  ------  ------  ------
(Clown Noses)       6608        7167        9579        3152
(Floppy Shoes)        89        99        23        84
********

However if I change to using the  esb.do(" ...mdx...") and then print the rows using:
rows = list(esb.rows())
for row in rows:
    print (row)

Then the output does not have the Axis-1.  It looks like this:

[b'(Clown Noses)', 6608, 7167, 9579, 3152]
[b'(Floppy Shoes)', 89, 99, 23, 84]

Is the Axis-1 supposed to be in the result list?
My Essbase.py has     MAXL_MDXCELLSTRSZ           = 1024 + 3

Thanks much,
flummoxify

**Comment by nurzen** [comment]
Hello,
when you use execute the output is generated by the function tdf(). In this function the Axis-1 information is  displayed via fetch_desc(). You have to call print(esb.fetch_desc()) before you list the rows.
Result looks like this.
``
((b'Axis-1', b'(Qtr1, Colas)', b'(Qtr2, Root Beer)'), (6, 8, 8))
[b'(East)', b'2747', b'610']
[b'(West)', b'1042', b'2423']
(1241150, 0, b'MDX Query execution completed')

**Comment by flummoxify** [comment]
Super Nurzen.  I appreciate the information.
