### ISSUE TITLE
MDX query returns no row

### ISSUE THREAD

**Issue by regiscabaret** [jasonwjones/essbasepy#3]
Hi there,
I can't get a MDX query to return the resultset

```
import Essbase
esb = Essbase.Essbase()

esb.connect('xxx','xxx','xxx')

stmts = [
	"alter session set dml_output alias off",
	"alter session set dml_output metadata_only on",
	"SELECT NON EMPTY CrossJoin(Descendants([ALL ENTITIES],10,LEAVES),Descendants([BUSINESS LINE],10,LEAVES)) ON ROWS, {[YTD]} ON COLUMNS FROM [FCRSSG].[FCRS] WHERE {([A2_01],[ACT],[PARTNER ENTITY],[FY16],[M5],[PRODUCT],[CUSTOMER],[COST CENTER],[ACCOUNT NATURE],[Adjusted])}"
]

for stmt in stmts:
	esb.execute(stmt)
	
esb.disconnect()
```

It returns

 ERROR - 1241202 - The most recent MaxL statement did not produce any output

Although the same statement inside MaxL works fine.

![image](https://cloud.githubusercontent.com/assets/3406265/15892231/3e6d15a6-2dab-11e6-887f-da4855a767ca.png)

Does essbasepy support MDX queries? If it does, am I missing something?

Thanks,

Regis

**Comment by regiscabaret** [comment]
OK, I found the problem. I need to indicate it is a MDX query: esb.bMdxQuery = True

**Comment by jasonwjones** [comment]
Hi Regis,

Glad you were able to find the problem! I’ll see if I can enhance the documentation based on this.

Thanks,

--
Jason Jones
http://www.linkedin.com/in/jaswjones
jason@saxifrages.com | Saxifrage Systems LLC
206-227-5719


On June 9, 2016 at 2:55:12 AM, Regis Cabaret (notifications@github.com) wrote:

OK, I found the problem. I need to indicate it is a MDX query: esb.bMdxQuery = True

**Comment by mwz293** [comment]
Had the same issue: thanks for the answer @regiscabaret. Why wouldn't the code default to MDX query = True, @jasonwjones?

**Comment by mwz293** [comment]
@jasonwjones I have a query that runs without any technical errors; however, the `esb.execute()` command only returns the `ON ROWS` and column headers.... but no actual data. I can run the same MDX query in SmartView in Excel and it works correctly and returns data. Any thoughts on what I may be missing? I am going through the `Essbase.py` file to run the code in the function to see where it breaks down.

**Comment by regiscabaret** [comment]
Can you share your code?

**Comment by mwz293** [comment]
Hopefully this will do....

`SELECT 
	NON EMPTY 
		{[dimensionONE_MEMBER_NAME]} 
	ON ROWS, 
		{[dimensionTWO_NAME].memberOne} 
	ON COLUMNS 
FROM [Database.CUBENAME] 
WHERE ([dimThree].[dimThreeVAL], [dimFour].[dimFourVAL], [dimFive].dimFiveVAL, [dimSix].dimSivVAL, [dimSeven].dimSevenVAL)`

**Comment by er77** [comment]
and reproduce on Sample.Basic ?)

**Comment by regiscabaret** [comment]
I mean the whole python code

<-- Regis Cabaret

On October 5, 2017 at 20:36:58, mwz293 (notifications@github.com) wrote:

Hopefully this will do....

SELECT NON EMPTY {[dimensionONE_MEMBER_NAME]} ON ROWS,
{[dimensionTWO_NAME].memberOne} ON COLUMNS FROM [Database.CUBENAME] WHERE
([dimThree].[dimThreeVAL], [dimFour].[dimFourVAL], [dimFive].dimFiveVAL,
[dimSix].dimSivVAL, [dimSeven].dimSevenVAL)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jasonwjones/essbasepy/issues/3#issuecomment-334451581>,
or mute the thread

**Comment by mwz293** [comment]
Oh sorry about that @regiscabaret ... yep, here is the code

`
import Essbase
import ctypes
esb = Essbase.Essbase()

#connect
esb.connect('username', 'password', 'hostname')

#set query to MDX query
esb.bMdxQuery = True

#execute query
esb.execute("SELECT NON EMPTY {[dimensionONE_MEMBER_NAME]} ON ROWS, {[dimensionTWO_NAME].memberOne} ON COLUMNS FROM [Database.CUBENAME] WHERE ([dimThree].[dimThreeVAL], [dimFour].[dimFourVAL], [dimFive].dimFiveVAL, [dimSix].dimSivVAL, [dimSeven].dimSevenVAL)")

#disconnect
esb.disconnect()`

**Comment by mwz293** [comment]
@er77 This is basically my query in Sample.Basic

`SELECT 
		{[100-10]}
	ON ROWS, 

		{[Qtr1]} 
	ON COLUMNS 
FROM Sample.Basic 
where ([Measures].[Profit])
`

**Comment by regiscabaret** [comment]
Why do you import types? You don’t need it, it’s already taken care of by
Essbase.py.

To capture the resultset, call esb.rows()

Try this:

*import Essbase*

*esb = Essbase.Essbase()*

*#connect*
*esb.connect('username', 'password', 'hostname')*

*#set query to MDX query*
*esb.bMdxQuery = True*

*#execute query*
*esb.do("SELECT NON EMPTY {[dimensionONE_MEMBER_NAME]} ON ROWS,
{[dimensionTWO_NAME].memberOne} ON COLUMNS FROM [Database.CUBENAME] WHERE
([dimThree].[dimThreeVAL], [dimFour].[dimFourVAL], [dimFive].dimFiveVAL,
[dimSix].dimSivVAL, [dimSeven].dimSevenVAL)")*

*#fetch the resultset*
*rows = esb.rows()*

*#Iterate through the rows*
*for row in rows: print(row)*

*#disconnect*
*esb.disconnect()*


<-- Regis Cabaret

On October 5, 2017 at 21:02:09, mwz293 (notifications@github.com) wrote:

Oh sorry about that @regiscabaret <https://github.com/regiscabaret> ...
yep, here is the code

`
import Essbase
import ctypes
esb = Essbase.Essbase()

#connect
esb.connect('username', 'password', 'hostname')

#set query to MDX query
esb.bMdxQuery = True

#execute query
esb.execute("SELECT NON EMPTY {[dimensionONE_MEMBER_NAME]} ON ROWS,
{[dimensionTWO_NAME].memberOne} ON COLUMNS FROM [Database.CUBENAME] WHERE
([dimThree].[dimThreeVAL], [dimFour].[dimFourVAL], [dimFive].dimFiveVAL,
[dimSix].dimSivVAL, [dimSeven].dimSevenVAL)")

#disconnect
esb.disconnect()`

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jasonwjones/essbasepy/issues/3#issuecomment-334457818>,
or mute the thread

**Comment by mwz293** [comment]
Touche on the ctype import... not sure why that was still in there. 

I did try `rows = esb.rows()`, but once I define the variable and do `[row for row in rows]`, I get a blank list `[]`... thoughts?

**Comment by mwz293** [comment]
If I run the exact query in SmartView in Excel it returns data correctly... So I know its not a query issue.

**Comment by regiscabaret** [comment]
esb.rows() is a list

If you do "[row for row in rows]”, it’s not doing anything.

what is len(esb.rows()) returning? or [print(row) for row in rows]



<-- Regis Cabaret

On October 5, 2017 at 21:19:16, mwz293 (notifications@github.com) wrote:

Touche on the ctype import... not sure why that was still in there.

I did try rows = esb.rows(), but once I define the variable and do [row for
row in rows], I get a blank list []... thoughts?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jasonwjones/essbasepy/issues/3#issuecomment-334462156>,
or mute the thread

**Comment by mwz293** [comment]
`len(esb.rows())` gives me a `TypeErrror: object of 'generator' has no len()` 

Sure enough: 
`>>> type(esb.rows())
<type 'generator'>`

**Comment by regiscabaret** [comment]
What about [print(row) for row in rows]

<-- Regis Cabaret

On October 5, 2017 at 21:26:37, mwz293 (notifications@github.com) wrote:

len(esb.rows()) gives me a TypeErrror: object of 'generator' has no len()

Sure enough:
>>> type(esb.rows()) <type 'generator'>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jasonwjones/essbasepy/issues/3#issuecomment-334464105>,
or mute the thread

**Comment by mwz293** [comment]
`[print(row) for row in rows]` gives me a syntax error and `for row in rows: print (row)` doesn't return anything

**Comment by regiscabaret** [comment]
What version of python are you using?

<-- Regis Cabaret

On October 5, 2017 at 21:29:51, mwz293 (notifications@github.com) wrote:

[print(row) for row in rows] gives me a syntax error and for row in rows:
print (row) doesn't return anything

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jasonwjones/essbasepy/issues/3#issuecomment-334465036>,
or mute the thread

**Comment by mwz293** [comment]
2.7.5 64 bit

**Comment by regiscabaret** [comment]
Ah… ok.

I use python 3.5. Some function calls are different in 2.7, like print. You
may have to cast the generator into a list as well.

Then try that:

import Essbase

esb = Essbase.Essbase()

#connect
esb.connect('username', 'password', 'hostname')

#set query to MDX query
esb.bMdxQuery = True

#execute query
esb.do("SELECT NON EMPTY {[dimensionONE_MEMBER_NAME]} ON ROWS,
{[dimensionTWO_NAME].memberOne} ON COLUMNS FROM [Database.CUBENAME] WHERE
([dimThree].[dimThreeVAL], [dimFour].[dimFourVAL], [dimFive].dimFiveVAL,
[dimSix].dimSivVAL, [dimSeven].dimSevenVAL)")

#fetch the resultset
rows = list(esb.rows())

#Iterate through the rows
for row in rows:

print row

#disconnect
esb.disconnect()


<-- Regis Cabaret

On October 5, 2017 at 21:31:41, mwz293 (notifications@github.com) wrote:

2.7.5 64 bit

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jasonwjones/essbasepy/issues/3#issuecomment-334465561>,
or mute the thread

**Comment by mwz293** [comment]
no dice

**Comment by regiscabaret** [comment]
I’ll try with 2.7 tomorrow. I can’t do it right now as I am at home (in
Singapore)

You see a message showing that it is loading the essmxl.dll successfully,
right? And it is connected to Essbase, is it?

<-- Regis Cabaret

On October 5, 2017 at 21:46:48, mwz293 (notifications@github.com) wrote:

no dice

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jasonwjones/essbasepy/issues/3#issuecomment-334469723>,
or mute the thread

**Comment by mwz293** [comment]
Yep, it is using the `essmxl.dll` and successfully connects to Essbase... The README says only use 2.7.5 64 bit .... did you get this working with python 3?

**Comment by regiscabaret** [comment]
Yes, it works like a charm with 3.5. We use it extensively.

All our Essbase jobs and more are written in python and use the Essbasepy
module. It changed our life… we’re big fans.

<-- Regis Cabaret

On October 5, 2017 at 21:51:27, mwz293 (notifications@github.com) wrote:

Yep, it is using the essmxl.dll and successfully connects to Essbase... The
README says only use 2.7.5 64 bit .... did you get this working with python
3?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jasonwjones/essbasepy/issues/3#issuecomment-334471065>,
or mute the thread

**Comment by mwz293** [comment]
Then, before you spend time on testing in 2.7.5, I'll take a swing at testing it in python `3.5` to see if that makes a difference

**Comment by mwz293** [comment]
No dice on `3.5`... I noticed that you asked about the `essmxl.dll` but I am using the `essmaxlu.dll`... make a difference?

**Comment by regiscabaret** [comment]
Nay, I meant essmaxlu.dll

If you have a way to remote control your environment, I can try to take a
closer look.

<-- Regis Cabaret

On October 5, 2017 at 22:22:26, mwz293 (notifications@github.com) wrote:

No dice on 3.5... I noticed that you asked about the essmxl.dll but I am
using the essmaxlu.dll... make a difference?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jasonwjones/essbasepy/issues/3#issuecomment-334480246>,
or mute the thread

**Comment by mwz293** [comment]
No, unfortunately, I don't have a way to do that....

**Comment by regiscabaret** [comment]
Can you send the whole code again? The one you use for python 3.5.

And a screen shot of the execution output.

<-- Regis Cabaret

On October 5, 2017 at 22:28:01, mwz293 (notifications@github.com) wrote:

No, unfortunately, I don't have a way to do that....

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jasonwjones/essbasepy/issues/3#issuecomment-334481989>,
or mute the thread

**Comment by mwz293** [comment]
Code hasn't change: see below

`
import Essbase

esb = Essbase.Essbase()

#connect
esb.connect('username', 'password', 'hostname')

#set query to MDX query
esb.bMdxQuery = True

#execute query
esb.do("SELECT NON EMPTY {[dimensionONE_MEMBER_NAME]} ON ROWS,
{[dimensionTWO_NAME].memberOne} ON COLUMNS FROM [Database.CUBENAME] WHERE
([dimThree].[dimThreeVAL], [dimFour].[dimFourVAL], [dimFive].dimFiveVAL,
[dimSix].dimSivVAL, [dimSeven].dimSevenVAL)")

#fetch the resultset
rows = list(esb.rows())

#Iterate through the rows
for row in rows:
print row

#disconnect
esb.disconnect()
`

**Comment by regiscabaret** [comment]
But the code for python 3.5 should be:

*import Essbase*

*esb = Essbase.Essbase()*

*#connect*
*esb.connect('username', 'password', 'hostname')*

*#set query to MDX query*
*esb.bMdxQuery = True*

*#execute query*
*esb.do("SELECT NON EMPTY {[dimensionONE_MEMBER_NAME]} ON ROWS,*
*{[dimensionTWO_NAME].memberOne} ON COLUMNS FROM [Database.CUBENAME] WHERE*
*([dimThree].[dimThreeVAL], [dimFour].[dimFourVAL], [dimFive].dimFiveVAL,*
*[dimSix].dimSivVAL, [dimSeven].dimSevenVAL)")*

*#fetch the resultset*
*rows = esb.rows()*

*#Iterate through the rows*
*for row in rows: **print(row)*

*#disconnect*
*esb.disconnect()*

On October 5, 2017 at 22:37:50, mwz293 (notifications@github.com) wrote:

Code hasn't change: see below

`
import Essbase

esb = Essbase.Essbase()

#connect
esb.connect('username', 'password', 'hostname')

#set query to MDX query
esb.bMdxQuery = True

#execute query
esb.do("SELECT NON EMPTY {[dimensionONE_MEMBER_NAME]} ON ROWS,
{[dimensionTWO_NAME].memberOne} ON COLUMNS FROM [Database.CUBENAME] WHERE
([dimThree].[dimThreeVAL], [dimFour].[dimFourVAL], [dimFive].dimFiveVAL,
[dimSix].dimSivVAL, [dimSeven].dimSevenVAL)")

#fetch the resultset
rows = list(esb.rows())

#Iterate through the rows
for row in rows:
print row

#disconnect
esb.disconnect()
`

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jasonwjones/essbasepy/issues/3#issuecomment-334485068>,
or mute the thread

**Comment by mwz293** [comment]
touche... save for those parentheses, nothing has changed

**Comment by mwz293** [comment]
@regiscabaret got it to work... code/MDX query wasn't the issue. Had to do with Essbase User permissions. Thanks for all the help all! Cheers!

**Comment by mwz293** [comment]
Below is my code and I am receiving the following error: `Error - 1241202 - The most recent MaxL statement did not produce any output.`

>>>import Essbase

esb = Essbase.Essbase()

#connect
esb.connect('username', 'password', 'hostname')

#set query to MDX query
esb.bMdxQuery = True

#execute query
esb.do("SELECT NON EMPTY {[dimensionONE_MEMBER_NAME]} ON ROWS,{[dimensionTWO_NAME].memberOne} ON COLUMNS FROM [Database.CUBENAME] WHERE([dimThree].[dimThreeVAL], [dimFour].[dimFourVAL], [dimFive].dimFiveVAL,[dimSix].dimSivVAL, [dimSeven].dimSevenVAL)")

#fetch the resultset
rows = esb.rows()

#Iterate through the rows
for row in rows: print(row)

#disconnect
esb.disconnect()

**Comment by mwz293** [comment]
Someone else on my team has run the above code and it returns the data correctly

**Comment by regiscabaret** [comment]
Instead of esb.do(), try with esb.execute() to see if it returns any error message that may explain you don't get any output

**Comment by mwz293** [comment]
My apologies: I was using `esb.execute()` and received the `Error - 1241202 - The most recent MaxL statement did not produce any output` error. Just tried `esb.do()` and after the print confirming that the script is using the `Maxl DLL`, the script ends with no print of the MDX query or output.

**Comment by regiscabaret** [comment]
And you’re using the same username as your team member?

<-- Regis Cabaret

On October 12, 2017 at 21:09:26, mwz293 (notifications@github.com) wrote:

My apologies: I was using esb.execute() and received the Error - 1241202 -
The most recent MaxL statement did not produce any output error. Just tried
esb.do() and after the print confirming that the script is using the Maxl
DLL, the script ends with no print of the MDX query or output.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jasonwjones/essbasepy/issues/3#issuecomment-336130056>,
or mute the thread

**Comment by mwz293** [comment]
No, I am not using the same username/pwd; however, if he runs the same script on his computer with my credentials, the script runs correctly and outputs the correct data.

**Comment by mwz293** [comment]
@regiscabaret  @jasonwjones As a follow up to all of my comments here, I found out my coworker was running a prior version of essbasepy. When I used his `Essbase.py` file, everything worked. The difference: `MAXL_MDXCELLSTRSZ           = 1024` and the newest version of essbasepy `MAXL_MDXCELLSTRSZ   = 1024 + 3`.

**Comment by nurzen** [comment]
Yeah i remember making that change, here the description
MAXL_MDXCELLSTRSZ in maxldefs.h is 1024+3 not 1024, fixes that Axis1 is not displayed correct when MDX is executed.
Look at your maxldefs.h the change happened with Essbase Version 11.1.2.4

**Comment by rpikkili** [comment]
Hi there,
    Will this work on linux environments? if what are the changes that we need to make?
