### ISSUE TITLE
Encoded numeric data in resultset

### ISSUE THREAD

**Issue by regiscabaret** [jasonwjones/essbasepy#8]
Hi there,
MDX query executed through essbasepy returns encoded data:

```
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import Essbase
>>> esb = Essbase.Essbase()
Using Maxl DLL in D:\Oracle\Middleware\EPMSystem11R1\common\EssbaseRTC-64\11.1.2.0\bin\essmaxlu.dll
>>> esb.connect('xxxxx','xxxxx','xxxxxx')
>>> esb.bMdxQuery = True
>>> esb.execute('select non empty Descendants([Market],10,LEAVES) on ROWS, [Year].Children on COLUMNS from Demo.Basic where {([Product],[Actual],[Sales])}')
Wed Mar 15 17:39:46 2017
MAXL> select non empty Descendants([Market],10,LEAVES) on ROWS, [Year].Children on COLUMNS from Demo.Basic where {([Product],[Actual],[Sales])};

Axis-1
------  -
(New_York)      52568384        52568400        52568416        52568368
(Boston)        52568352        52568560        52568576        52568592
(Chicago)       52568608        52568624        52568640        52568656
(San_Francisco) 52568672        52568688        52568704        52568720
(Seattle)       52568736        52568752        52568768        52568784
(Denver)        52568800        52568816        52568832        52568848
(Los_Angeles)   52568864        52568880        52576480        52576496
(Dallas)        52576512        52576528        52576544        52576560
(Houston)       52576576        52576592        52576608        52576624
(Phoenix)       52576640        52576656        52576672        52576688


 OK/INFO - 1241150 - MDX Query execution completed.

0
>>>
```

The same query run in MaxL client returns the correct numbers.

Am I missing something? Do I need to set something up to fetch the float values?

Thanks,

Regis

**Comment by jasonwjones** [comment]
In what way is it wrong? Is it that it's missing decimals and digits after the decimals?

**Comment by regiscabaret** [comment]
No, the numbers are just completely wrong, And oddly, they all have 8
digits.

If I run the same query in MaxL Essbase client or retrieve it in Smartview,
I get the right numbers.

<-- Regis Cabaret

On March 18, 2017 at 04:32:05, Jason Jones (notifications@github.com) wrote:

In what way is it wrong? Is it that it's missing decimals and digits after
the decimals?

**Comment by regiscabaret** [comment]
I think I've figured out where it's coming from:
in function **_MaxlMDXOutputNextRecord**, it's casting the MDX data output to c_long which is an int c_type.
I've tried different other c_type (c_float, c_double..). but none are returning the right value which should be:

```
MAXL> select non empty Descendants([Market],10,LEAVES) on ROWS, [Year].Children on COLUMNS from Demo.Basic where {([Product],[Actual],[Sales])};

 Axis-1              (Q1)                (Q2)                (Q3)                (Q4)
+-------------------+-------------------+-------------------+-------------------+-------------------
 (New_York)                        18631               17681               19923               24403
 (Boston)                          15812               15050               16716               19159
 (Chicago)                         16536               15599               17411               21374
 (San_Francisco)                   19761               19019               20722               24807
 (Seattle)                         13766               13546               14204               19034
 (Denver)                          13800               13588               13838               18232
 (Los_Angeles)                     17866               17269               17208               22635
 (Dallas)                           9226                9175                9481               12700
 (Houston)                          7690                7363                7646               10785
 (Phoenix)                          8157                7903                8343               11843

 OK/INFO - 1241150 - MDX Query execution completed.
```

Any suggestion?

**Comment by regiscabaret** [comment]
Any idea how to fix this?
I'd really like to be able to query data but I am stuck because of this issue.

**Comment by nurzen** [comment]
Hello,

i tried to reproduce the scenario and found a workaround.

As you mentioned the problem is the _MaxlMDXOutputNextRecord function and the cast to another type. I had a mdx query with nothing on the rows that only outputs two numbers where the first number is displayed correct with decimals and the second number isnt. Using the debugger i found out the the fldType was different (8 for the first number and 0 for the second).

The workaround is now to cast with a string no matter what fldType is. 

`
    def _MaxlMDXOutputNextRecord(self, sid, numFlds):
        row = []
        pHeader_t = POINTER(maxl_mdxoutputheader_t)
        pHeader = pHeader_t()

        #ESS_PPVOID_T ppRecord;
        #ppRecord = malloc(sizeof(ESS_PVOID_T) * ulNumCols)
        ppRecordAry = ESS_PVOID_T * numFlds
        ppRecord = ppRecordAry()

        sts = self.maxl.MaxlMDXOutputNextRecord(sid, ppRecord)
        if sts == MAXL_MSGLVL_SUCCESS:
            sts = self.maxl.MaxlMDXOutputDescribe(sid, byref(pHeader))
            if sts == MAXL_MSGLVL_SUCCESS:
                for index in range(numFlds):
                    row.append(cast(ppRecord[index], POINTER(c_char_p))[0])
                    
        return sts, row
`

I hope that helps.

Greets
Kevin

**Comment by regiscabaret** [comment]
Thanks Kevin! It works well now!
